### ISSUE TITLE
HOME environment variable vcpk install tools not detected by tool chain

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/vscode-environment-manager#2] opened 2023-08-23 09:51 UTC
If the HOME environment variable is set, vcpk does not install the tools in the .vcpk user directory.

This leads to the fact that the programs are not found, e.g. ninja.

In my case the HOME environment variable was created by another program and set to c:\SPB_Data

Type: Bug Report

**Describe the bug**
- OS and Version: Win11
- VS Code Version: 1.81.1
- Extension Version: 1.0.5
- Target Device:  FRDM-K32L3A6

**Comment by mcgordonite** [comment] 2023-08-29 15:08
Hi @FerdinandEn, can you check what is in the Environment output channel in VS Code when this error occurs?

**Comment by FerdinandEn** [comment] 2023-08-30 07:34
Hi @mcgordonite  , I deleted the HOME variable and reinstalled VSCode completely. After that everything worked. Unfortunately I can no longer reproduce the error like this.

**Comment by mcgordonite** [comment] 2023-08-30 10:44
Thanks for checking. I can't reproduce it on my Windows system either, so I'll close this issue for now. Please re-open if you see it again.

**Closed by mcgordonite** 2023-08-30 10:44 UTC
