### ISSUE TITLE
Environment activation fails to unpack arm-none-eabi-gcc package

### ISSUE THREAD

**Issue by AkiMakkonen-AlifSemi** [ARM-software/vscode-environment-manager#4] opened 2024-02-13 13:21 UTC
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.86.1
- Extension Version: 1.1.4

**To Reproduce**
1. Use clean environment (artifacts not unpacked)
2. Activate environment using the attached config
Unpacking of gcc is stalled. After a while environment activation fails and red X is shown in the bottom 'toolbar'. 

**Expected behavior**
Environment gets activated.

**logs**
[1/4] microsoft:tools/kitware/cmake already installed.
[2/4] microsoft:tools/ninja-build/ninja already installed.
[3/4] Installing arm:compilers/arm/arm-none-eabi-gcc...
Unpacking c:\Users\AkiMakkonen\.vcpkg\downloads\compilers.arm.arm-none-eabi-gcc-12.3.1-(d52888bf59c5262ebf3e6b19b9f9e6270ecb60fd218cf81a4e793946e805a654).zip...
Updating registry data from [https://github.com/microsoft/vcpkg-ce-catalog/archive/refs/heads/main.zip]
Updating registry data from arm
Updating registry data from microsoft
Updated registries at c:\workspace\alif_vscode-template_DEV\vcpkg-configuration.json
[1/4] microsoft:tools/kitware/cmake already installed.
[2/4] microsoft:tools/ninja-build/ninja already installed.
[3/4] Installing arm:compilers/arm/arm-none-eabi-gcc...
Unpacking c:\Users\AkiMakkonen\.vcpkg\downloads\compilers.arm.arm-none-eabi-gcc-12.3.1-(d52888bf59c5262ebf3e6b19b9f9e6270ecb60fd218cf81a4e793946e805a654).zip...

**config**
Tested vcpkg-configuration.json
```
{
  "registries": [
    {
      "kind": "artifact",
      "location": "https://aka.ms/vcpkg-ce-default",
      "name": "microsoft" 
    },
    {
      "kind": "artifact",
      "location": "https://artifacts.keil.arm.com/vcpkg-ce-registry/registry.zip",
      "name": "arm"
    }
  ],
  "requires": {
    "microsoft:cmake": "^3.25.2",
    "microsoft:ninja": "^1.10.2",
    "arm:compilers/arm/arm-none-eabi-gcc": "^12.2.1-0",
    "arm:tools/open-cmsis-pack/cmsis-toolbox": "^2.1.0-0"
  }
}
```

**Additional context**
Works in Ubuntu 22 with the same extension version.
Downgrading Arm Environment Manager to version 1.0.6 works.
So versions 1.1.0 to 1.1.4 seem to be affected.

**Comment by AkiMakkonen-AlifSemi** [comment] 2024-02-16 08:09
Tested with v1.1.5 and the problem is also there.

**Comment by thegecko** [comment] 2024-02-16 14:08
Thanks for the bug report.

We believe this is ultimately due to this issue: https://github.com/microsoft/vcpkg/issues/35429

Coupled with the fact we don't want to install the entirely of cmake in order to just unzip a package.

This requires further investigation on our side to see if we can find a workaround.

**Comment by thegecko** [comment] 2024-03-14 14:59
Apologies for the silence on this issue.

We believe it may be caused by windows path length limits. Please check you have long path names enabled. This can be done using the `csolution tool if you have this installed:

```bash
csolution list environment
```

Should yield `Long pathname support=enabled`

**Comment by thegecko** [comment] 2024-03-16 18:20
I have confirmed this is the issue, please know how you get on.

**Comment by AkiMakkonen-AlifSemi** [comment] 2024-03-18 10:14
Hi,
Yes the long pathname support was disabled by default in my Windows 11.
I enabled it by setting the LongPathsEnabled in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem registry

Seems to work now. Thanks!

**Comment by thegecko** [comment] 2024-03-18 10:16
Excellent news. We plan to detect this in an upcoming release to help others. I'll close this issue for now.

**Closed by thegecko** 2024-03-18 10:16 UTC
